/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clinicaapp.Utilidades;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import com.mycompany.clinicaapp.Utilidades.EventosParaBotones;

/**
 *
 * @author johan
 */
public class BotonesJtableMedico extends javax.swing.JPanel {

    /**
     * Creates new form BotonesJtableMedico
     */
    public BotonesJtableMedico() {
        initComponents();
        this.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

    }

    public void iniciarEvento(EventosParaBotones event, int row) {
        botonJtableMedico1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.clickHistorial(row);
            }
        });
        botonJtableMedico2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.clickEliminar(row);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonJtableMedico2 = new com.mycompany.clinicaapp.Utilidades.BotonJtableMedico();
        botonJtableMedico1 = new com.mycompany.clinicaapp.Utilidades.BotonJtableMedico();

        botonJtableMedico2.setIcon(new javax.swing.ImageIcon("C:\\Users\\johan\\OneDrive\\Documentos\\GitHub\\ClinicaApp\\ClinicaApp\\src\\main\\java\\com\\mycompany\\clinicaapp\\Imagenes\\TrashCan 20x20.png")); // NOI18N

        botonJtableMedico1.setIcon(new javax.swing.ImageIcon("C:\\Users\\johan\\OneDrive\\Documentos\\GitHub\\ClinicaApp\\ClinicaApp\\src\\main\\java\\com\\mycompany\\clinicaapp\\Imagenes\\Historial 20x20.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonJtableMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonJtableMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonJtableMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonJtableMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.clinicaapp.Utilidades.BotonJtableMedico botonJtableMedico1;
    private com.mycompany.clinicaapp.Utilidades.BotonJtableMedico botonJtableMedico2;
    // End of variables declaration//GEN-END:variables
}
